#ifndef JUGADORES_H_INCLUDED
#define JUGADORES_H_INCLUDED
#include "cartones.h"

struct JugadorE;
struct ComputadoraE;


typedef struct JugadorE * Jugador;
typedef struct ComputadoraE * Computadora;

//------------funciones---------------//
//PRE:DEBE EXISTIR LA STRUCT CON SUS DATOS. Jugador ES, POR EL typedef UN TIPO DE DATO STRUCT HECHO PUNTERO Y QUE APUNTA A LA STRUCT JugadorE
//POST:SE CARGAN LOS DATOS DEL JUGADOR POR CONSOLA
Jugador cargarJugadorPorTeclado ();
//PRE:DEBE EXISTIR LA STRUCT CON SUS DATOS. Computadora ES, POR EL typedef UN TIPO DE DATO STRUCT HECHO PUNTERO Y QUE APUNTA A LA STRUCT ComputadoraE
//POST:SE CARGAN LOS DATOS DEL JUGADOR POR CONSOLA
Computadora cargarJugadorPc ();
//PRE: DEBEN ESTAR DECLARADOS LOS DATOS Computadora Y Jugador HECHOS POR typedef. SE LOS PASA POR PARÁMETRO
//POST:SE MUESTRAN LOS PUNTAJES DEL JUGADOR Y LA PC
void mostrarPuntajes(Jugador m ,Computadora p);
//PRE:EL PUNTERO QUE APUNTA A LA STRUCT ES UN TIPO DE DATO. OTRA VARIABLE PUNTAJE QUE FUNCIONA COMO BANDERA
//POST:PERMITE CAMBIAR LOS PUNTAJES CARGADOS EN EL JUGADOR
void setPuntaje( Jugador j, int puntaje);


//--------------gets------------------//
//PRE:Jugador DEBE ESTAR DECLARADO COMO PUNTERO. 
//POST:RETORNA EL NOMBRE Y APELLIDO DEL USUARIO
char* getNombreYapellido(Jugador j);
//PRE:EL PUNTERO QUE APUNTA A LA STRUCT ES UN TIPO DE DATO. OTRA VARIABLE PUNTAJE QUE FUNCIONA COMO BANDERA
//POST:PERMITE CAMBIAR LOS PUNTAJES CARGADOS EN LA PC
void setPuntajePc( Computadora p, int puntaje);

//PRE:Jugador ES UN PUNTERO. SE LO PASA POR PARÁMTRO
//POST:RETORNA EL PUNTAJE DEL USUARIO COMO FLOAT
float getPuntaje(Jugador j);
//PRE:Computadora ES UN PUNTERO. SE LO PASA POR PARÁMTRO
//POST:RETORNA EL PUNTAJE DE LA PC COMO FLOAT
float getPuntajePc(Computadora p);
//PRE: EL ARCHIVO DEBE ESTAR CREADO. SE PASA POR PARÁMETRO LAS STRUCT PARA ACCEDER EN EL CUERPO A LOS PUNTAJE
//POST:SE GUARDAN LOS PUNTAJES DE LA PC Y EL JUGADOR EN UN TXT
void guardarPuntajes (Jugador ju,Computadora pc);
//PRE: EL ARCHIVO DEBE ESTAR CREADO EN FORMATO TXT.
//POST:LEE LOS PUNTAJES GUARDADOS EN ARCHIVO Y LOS MUESTRA POR CONSOLA
void leerPuntajes();


#endif // JUGADORES_H_INCLUDED
